# Generated by Django 5.0.4 on 2024-04-20 09:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spent_date", models.DateField(default=datetime.datetime.today)),
                ("spent_by", models.CharField(max_length=100)),
                (
                    "spent_category",
                    models.CharField(
                        choices=[
                            ("", "Select Category"),
                            ("HOME", "HOME"),
                            ("MEDICINE", "MEDICINE"),
                            ("FARM", "FARM"),
                            ("TRAVEL", "TRAVEL"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "spent_method",
                    models.CharField(
                        choices=[
                            ("", "Select Method"),
                            ("CASH", "CASH"),
                            ("CREDIT", "CREDIT"),
                            ("DEBIT", "DEBIT"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=100,
                    ),
                ),
                ("spent_amount", models.PositiveIntegerField()),
                ("spent_note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("", "Select Priority"),
                            ("High", "HIGH"),
                            ("Low", "LOW"),
                            ("Medium", "MEDIUM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
